#!/usr/bin/env bash
# Clone service repos listed in scripts/service-repos.list (read-only; never push).
# Writes CLONE_ROOT/repos-manifest.yaml with cloned commit/branch/remote metadata.
set -euo pipefail

ORCHESTRATION_SRC="${ORCHESTRATION_SRC:-${CODEBUILD_SRC_DIR:-.}}"
CLONE_ROOT="${CLONE_ROOT:-/tmp/repos}"
LIST_FILE="${SERVICE_REPOS_LIST:-$ORCHESTRATION_SRC/scripts/service-repos.list}"
REPOS_MANIFEST="${REPOS_MANIFEST:-${CLONE_ROOT}/repos-manifest.yaml}"

if [[ ! -f "$LIST_FILE" ]]; then
  echo "Missing service list: $LIST_FILE" >&2
  exit 1
fi

mkdir -p "$CLONE_ROOT"
FAILED=0

while IFS= read -r line || [[ -n "$line" ]]; do
  [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
  IFS='|' read -r NAME PATH_REL REMOTE BRANCH <<< "$line"
  DEST="${CLONE_ROOT}/${PATH_REL}"
  echo "==== Cloning ${REMOTE} -> ${DEST} (branch=${BRANCH}) ===="
  rm -rf "$DEST"
  CLONE_ARGS=(--depth 1)
  if [[ -n "$BRANCH" && "$BRANCH" != "-" ]]; then
    CLONE_ARGS+=(--branch "$BRANCH")
  fi
  if git clone "${CLONE_ARGS[@]}" "$REMOTE" "$DEST"; then
    git -C "$DEST" remote set-url --push origin DISABLED
    git -C "$DEST" config user.name "codebuild-readonly"
    git -C "$DEST" config user.email "noreply@invalid"
    git -C "$DEST" log -1 --oneline
    git -C "$DEST" remote -v
  else
    echo "FAILED: $REMOTE"
    FAILED=1
  fi
done < "$LIST_FILE"

echo "==== Clone summary ===="
ls -la "$CLONE_ROOT"
for d in "$CLONE_ROOT"/*; do
  [[ -d "$d" ]] || continue
  if [[ -d "$d/.git" ]]; then
    echo "OK  $(basename "$d")"
  else
    echo "MISS $(basename "$d")"
  fi
done

if [[ "$FAILED" -ne 0 ]]; then
  echo "One or more service clones failed" >&2
  exit 1
fi

echo "==== Writing repos-manifest.yaml ===="
python3 - "$CLONE_ROOT" "$REPOS_MANIFEST" "$LIST_FILE" <<'PY'
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

clone_root = Path(sys.argv[1])
manifest_path = Path(sys.argv[2])
list_file = Path(sys.argv[3])


def git_out(path: Path, *args: str) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(path), *args],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def entry_for(path_rel: str, name: str = "", requested_branch: str = "", requested_remote: str = "") -> dict:
    path = clone_root / path_rel
    commit = git_out(path, "rev-parse", "HEAD") if path.is_dir() else ""
    branch = git_out(path, "branch", "--show-current") if path.is_dir() else ""
    remote = git_out(path, "remote", "get-url", "origin") if path.is_dir() else ""
    # Prefer list remote before push was disabled; fall back to configured origin.
    if remote in ("", "DISABLED") and requested_remote:
        remote = requested_remote
    return {
        "name": name or path_rel.replace("/", "-"),
        "path": path_rel,
        "branch": branch or requested_branch or "unknown",
        "commit": commit or "0000000000000000000000000000000000000000",
        "remote": remote,
        "source": "service-repos.list" if name else "clone-root",
    }


repos = []
seen = set()
for line in list_file.read_text(encoding="utf-8").splitlines():
    line = line.strip()
    if not line or line.startswith("#"):
        continue
    parts = line.split("|")
    if len(parts) < 3:
        continue
    name, path_rel, remote = parts[0], parts[1], parts[2]
    branch = parts[3] if len(parts) > 3 else "-"
    if branch == "-":
        branch = ""
    repos.append(entry_for(path_rel, name=name, requested_branch=branch, requested_remote=remote))
    seen.add(path_rel)

# Include packaging/orchestration checkouts already under CLONE_ROOT (e.g. S3 bundles).
for child in sorted(clone_root.iterdir()):
    if not child.is_dir() or not (child / ".git").exists():
        continue
    rel = child.name
    if rel in seen:
        continue
    repos.append(entry_for(rel))

lines = [
    "# Auto-generated by ci/aws/clone-service-repos.sh at clone time.",
    "",
    "clone:",
    f'  built_at: "{datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}"',
    f'  built_by: "{os.environ.get("CODEBUILD_BUILD_ID", os.environ.get("CODEBUILD_INITIATOR", ""))}"',
    f'  clone_root: "{clone_root}"',
    "",
    "repos:",
]
for repo in repos:
    lines.extend([
        f"  - name: {repo['name']}",
        f"    path: {repo['path']}",
        f"    branch: {repo['branch']}",
        f'    commit: "{repo["commit"]}"',
        f'    remote: "{repo["remote"]}"',
        f"    source: {repo['source']}",
        "",
    ])

manifest_path.write_text("\n".join(lines), encoding="utf-8")
print(manifest_path)
PY

echo "==== repos-manifest.yaml ===="
sed -n '1,80p' "$REPOS_MANIFEST"
