#!/usr/bin/env bash
# Generate or verify release-manifest.yaml for guesttek-camsuite-edge builds.
#
# Usage:
#   ./scripts/release-manifest.sh generate [--output release-manifest.yaml] [--platform amd64] [--date-tag YYYYMMDD]
#   ./scripts/release-manifest.sh verify [--manifest release-manifest.yaml] [--strict]
#
# Requires: python3 (stdlib only)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MANIFEST="${ROOT}/release-manifest.yaml"
PLATFORM=""
DATE_TAG=""
PACKAGE_VERSION=""

# Service repos only (GitHub + Bitbucket). deploy/ and guesttek-camsuite-edge/ are
# orchestration/packaging and are supplied separately (bundles or local checkout).
REPO_PATHS=(
  camsuite-emb-ip-camera
  camsuite-emb-video-capture
  suspicious_objects_inference_service
  alert_manager_service
  camsuite-emb-mqtt-client
  camsuite-emb-video-upload-manager
  camsuite-emb-provisioning
  camsuite-emb-pre-provisioning
)

usage() {
  sed -n '2,7p' "$0" | sed 's/^# \?//'
  exit "${1:-0}"
}

log() { echo "==> $*"; }
die() { echo "Error: $*" >&2; exit 1; }

git_head() {
  local dir="$1"
  git -C "$dir" rev-parse HEAD 2>/dev/null || echo ""
}

git_branch() {
  local dir="$1"
  git -C "$dir" branch --show-current 2>/dev/null || echo ""
}

read_package_version() {
  if command -v dpkg-parsechangelog >/dev/null 2>&1; then
    dpkg-parsechangelog -S Version -l "${ROOT}/guesttek-camsuite-edge/debian/changelog" 2>/dev/null || true
  fi
}

cmd_generate() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --output) MANIFEST="$2"; shift 2 ;;
      --platform) PLATFORM="$2"; shift 2 ;;
      --date-tag) DATE_TAG="$2"; shift 2 ;;
      -h|--help) usage 0 ;;
      *) die "Unknown argument: $1" ;;
    esac
  done

  PLATFORM="${PLATFORM:-amd64}"
  DATE_TAG="${DATE_TAG:-$(date -u +%Y%m%d)}"
  PACKAGE_VERSION="$(read_package_version)"
  PACKAGE_VERSION="${PACKAGE_VERSION:-unknown}"

  python3 - "$ROOT" "$MANIFEST" "$PLATFORM" "$DATE_TAG" "$PACKAGE_VERSION" "${REPO_PATHS[@]}" <<'PY'
import sys
from datetime import datetime, timezone
from pathlib import Path

root = Path(sys.argv[1])
manifest_path = Path(sys.argv[2])
platform = sys.argv[3]
date_tag = sys.argv[4]
package_version = sys.argv[5]
repo_paths = sys.argv[6:]

def git_head(path: Path) -> str:
    import subprocess
    try:
        return subprocess.check_output(
            ["git", "-C", str(path), "rev-parse", "HEAD"],
            text=True,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "0000000000000000000000000000000000000000"

def git_branch(path: Path) -> str:
    import subprocess
    try:
        out = subprocess.check_output(
            ["git", "-C", str(path), "branch", "--show-current"],
            text=True,
        ).strip()
        return out or "unknown"
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"

def git_remote(path: Path) -> str:
    import subprocess
    try:
        return subprocess.check_output(
            ["git", "-C", str(path), "remote", "get-url", "origin"],
            text=True,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""

lines = [
    "# Auto-generated by scripts/release-manifest.sh — commit before publishing.",
    "",
    "release:",
    f'  package_version: "{package_version}"',
    f'  date_tag: "{date_tag}"',
    f'  platform: {platform}',
    f'  label: "edge-{date_tag}-{platform}"',
    f'  built_at: "{datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}"',
    '  built_by: ""',
    "  artifacts:",
    f'    deb: "guesttek-camsuite-edge_{package_version}_{platform}.deb"',
    f'    image_tar: "guesttek-camsuite-edge/docker/camsuite-images-{platform}.tar"',
    f'    image_archive: "deploy/guesttek-camsuite-edge-{date_tag}.tar"',
    "",
    "repos:",
]

for rel in repo_paths:
    path = root / rel
    name = rel.replace("/", "-")
    commit = git_head(path) if path.is_dir() else "0000000000000000000000000000000000000000"
    branch = git_branch(path) if path.is_dir() else "missing"
    remote = git_remote(path) if path.is_dir() else ""
    lines.extend([
        f"  - name: {name}",
        f"    path: {rel}",
        f"    branch: {branch}",
        f'    commit: "{commit}"',
    ])
    if remote:
        lines.append(f'    remote: "{remote}"')
    lines.append("")

manifest_path.write_text("\n".join(lines), encoding="utf-8")
print(manifest_path)
PY

  log "Wrote ${MANIFEST}"
}

cmd_verify() {
  local strict=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --manifest) MANIFEST="$2"; shift 2 ;;
      --strict) strict=1; shift ;;
      -h|--help) usage 0 ;;
      *) die "Unknown argument: $1" ;;
    esac
  done

  [[ -f "$MANIFEST" ]] || die "Manifest not found: ${MANIFEST}"

  python3 - "$ROOT" "$MANIFEST" "$strict" <<'PY'
import re
import sys
from pathlib import Path

root = Path(sys.argv[1])
manifest_path = Path(sys.argv[2])
strict = sys.argv[3] == "1"
text = manifest_path.read_text(encoding="utf-8")

# Minimal YAML parser for this fixed schema (no PyYAML dependency).
repos = []
current = {}
for line in text.splitlines():
    m = re.match(r"^\s*-\s+name:\s+(\S+)", line)
    if m:
        if current:
            repos.append(current)
        current = {"name": m.group(1)}
        continue
    for key in ("path", "branch", "commit"):
        m = re.match(rf'^\s+{key}:\s+"?([^"#]+?)"?\s*(#.*)?$', line)
        if m and current is not None:
            current[key] = m.group(1).strip().strip('"')
            break
if current:
    repos.append(current)

if not repos:
    sys.exit("Error: no repos found in manifest")

errors = 0
for repo in repos:
    rel = repo.get("path", "")
    expected = repo.get("commit", "")
    name = repo.get("name", rel)
    path = root / rel

    if expected == "0000000000000000000000000000000000000000":
        if strict:
            print(f"  FAIL placeholder commit: {name}", file=sys.stderr)
            errors += 1
        else:
            print(f"  SKIP (placeholder): {name}")
        continue

    if not path.is_dir():
        print(f"  FAIL missing dir: {rel}", file=sys.stderr)
        errors += 1
        continue

    import subprocess
    try:
        actual = subprocess.check_output(
            ["git", "-C", str(path), "rev-parse", "HEAD"], text=True
        ).strip()
    except subprocess.CalledProcessError:
        print(f"  FAIL not a git repo: {rel}", file=sys.stderr)
        errors += 1
        continue

    if actual != expected:
        print(f"  FAIL {name}: expected {expected[:12]}… got {actual[:12]}…", file=sys.stderr)
        errors += 1
    else:
        print(f"  OK   {name}: {actual[:12]}…")

# release.date_tag / platform sanity (optional fields)
m = re.search(r'^\s*date_tag:\s*"(\d{8})"', text, re.M)
if m:
    print(f"==> manifest date_tag: {m.group(1)}")
m = re.search(r'^\s*platform:\s*(\S+)', text, re.M)
if m:
    print(f"==> manifest platform: {m.group(1)}")

if errors:
    sys.exit(f"Error: {errors} repo(s) failed verification.")
print("==> Manifest verification passed.")
PY
}

main() {
  [[ $# -ge 1 ]] || usage 1
  case "$1" in
    generate) shift; cmd_generate "$@" ;;
    verify)   shift; cmd_verify "$@" ;;
    -h|--help) usage 0 ;;
    *) die "Unknown command: $1 (try generate|verify)" ;;
  esac
}

main "$@"
